// Make a GET request to the 'https://swapi.co/api/films/?format=json' URL
$.get('https://swapi.co/api/films/?format=json', function (data) {
  // Inside the callback function:

  // Use the jQuery .append() method to add list items for each movie title to the <UL> element with the id 'list_movies'
  $('UL#list_movies').append(
    // Use the spread operator (...) to spread the array of list items generated by the map function
    ...data.results.map(movie => `<li>${movie.title}</li>`)
  );
});
